### ISSUE TITLE
Toast Center Top and Center Bottom

### ISSUE THREAD

**Issue by aguilera51284** [apvarun/toastify-js#10]
is that, by the way that good lib :)!

**Comment by apvarun** [comment]
I think what you mean is to provide options to position the toast to the center (top and bottom) in desktop as like in mobile. Am I right ?

**Comment by aguilera51284** [comment]
yes! sorry for the bad context :(

**Comment by eriktobben** [comment]
Love the library! Has this feature been added? :)

**Comment by Ehsan-Home** [comment]
Hi. 
Has this feature added? 💯

**Comment by apvarun** [comment]
This feature has been added in version 1.6.0
@eriktobben @Ehsan-Home @aguilera51284
