### ISSUE TITLE
Doesn't play well with TailwindCSS (or any other utility framework)

### ISSUE THREAD

**Issue by gremo** [apvarun/toastify-js#101]
... because of the style `background: linear-gradient(135deg, #73a5ff, #5477f5)` applied by default. 

TailwindCSS uses the `bg-` utility class to change the background color. Passing the option `className` doesn't work of course, because of the background property:

![toastify](https://user-images.githubusercontent.com/1532616/167439733-6d2bc587-01d7-485c-be1a-08be6d8f8c9c.PNG)

This is annoying because most of the time the primary purpose is to change the background color. Is there a way to unset (maybe using some options) the background itself, and use my `bg-green-500` class?

**Comment by Shitric** [comment]
I think you can unset the background property for default and set className to bg-green-500. Maybe i'm wrong but give a change :)

**Comment by gremo** [comment]
@Shitric thanks for helping, but `unset` wins:

![Immagine 2022-05-16 161546](https://user-images.githubusercontent.com/1532616/168613389-59951af2-80e1-439e-a0b1-fd6fcefc0a27.png)

**Comment by apvarun** [comment]
Importing the toastify css file before the tailwind layers in your CSS file would change the specificity as per your need. 
Can you try it @gremo ?

**Comment by gremo** [comment]
@apvarun well that is not simple. I'm lazy loading the css needed by toastify-js

**Comment by gremo** [comment]
Solved using `important` modifier this way: `!bg-none !bg-cyan-500`. But I still think there should better way. I'll close this for not polluting the issues.
