### ISSUE TITLE
Avoid duplicate

### ISSUE THREAD

**Issue by siandrealves** [apvarun/toastify-js#103]
I believe there's no param to avoid duplications of the same window, right?
Is there any way to prevent it (user is clicking multiple times on a button and opening multiple warnings)?

(it would be a cool option for the future - request)

**Comment by apvarun** [comment]
Hi @siandrealves,
I believe this should be done based on your use case in your custom code.
As a library, implementing this would mean also adding ways to detect if the clicks were duplicate and also adding time between multiple clicks and so on. That's not the problem the package is addressing. Hope that makes sense.

**Comment by peterlaws** [comment]
Most other libraries have the option to stop duplicates... but you're right, this can be done via code...... But I still think it's a worthy option.
