### ISSUE TITLE
TypeError Exports

### ISSUE THREAD

**Issue by Mmisiek** [apvarun/toastify-js#121]
Suddenly in my Flutter project, I get the error:
TypeError: Cannot read properties of null (reading 'exports')
assets/packages/fluttertoast/assets/toastify.js 14:48  <fn>
assets/packages/fluttertoast/assets/toastify.js 14:90  <fn>

Any idea what could have changed ?

**Comment by josemoura212** [comment]
I have the same message if anyone knows how to solve it

**Comment by Mmisiek** [comment]
New version fixed this issue.

**Comment by Mmisiek** [comment]
Fixed in version 8.2.2 https://pub.dev/packages/fluttertoast/versions/8.2.2

**Comment by josemoura212** [comment]
I fixed this error, but I couldn't use toast on the web, I switched to bot toast but I didn't like it very much, I think it's heavier, could you help me?

**Comment by Mmisiek** [comment]
Sorry, I don't understand your problem. I am using this package non-directly. I updated the version to ^8.2.2 in my pubsec.yalm and it works.

**Comment by josemoura212** [comment]
Now it worked, I forgot to uncomment fluttertoast, thanks anyway

**Comment by josemoura212** [comment]
I have another error, if you knew could you help me.
WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.

**Comment by Mmisiek** [comment]
> I have another error, if you knew could you help me. WARNING: found an existing tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.

Sorry, never seen it.
