### ISSUE TITLE
Missing Github release, version mismatching

### ISSUE THREAD

**Issue by d4rn0k** [apvarun/toastify-js#13]
Hello,

please update that: https://github.com/apvarun/toastify-js/releases to corresponds actual releases available in https://github.com/apvarun/toastify-js/blob/master/CHANGELOG.md file.

Mainly because, I can't download this library via bower install:

bower.json:
`"toastify-js": "apvarun/toastify-js#^1.3.1"`

produces:

> **bower install**  
>                                                                        
> bower toastify-js#^1.3.1    not-cached https://github.com/apvarun/toastify-js.git#^1.3.1 
> bower toastify-js#^1.3.1       resolve https://github.com/apvarun/toastify-js.git#^1.3.1 
> bower toastify-js#^1.3.1  ENORESTARGET No tag found that was able to satisfy ^1.3.1      
>  
> Additional error details:                                                                
> Available versions in https://github.com/apvarun/toastify-js.git: 1.1.0, 1.0.0, 0.0.1

**Comment by apvarun** [comment]
Updated the release v1.3.1
