### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by peaceful-james** [apvarun/toastify-js#135]
I am just checking if this repo is still being maintained.

There are good PRs since last year with no feedback and the last commit was a year ago.

If there is no response, I will assume this repo has been abandoned.

**Comment by apvarun** [comment]
Hey @peaceful-james , I have been receiving more features requests that defeat the purpose of having a simple and minimal package that is easy to use and does just one thing. Hence, there are PR's that are open. They don't fix any issues for existing users, rather adds more features, bloating the package.
