### ISSUE TITLE
Feature Request: Disable Timeout on Focus

### ISSUE THREAD

**Issue by BrookeDot** [apvarun/toastify-js#21]
Toast is great, one feature that would be helpful is an option to disable the timeout feature on a notification when it has focus (hover or touch). This would allow visitors to focus on longer messages giving them time to read the whole thing without it disappearing. Maybe the option could be `hideOnFocus:` and then be set to `true` or `false`. 

For context, this was bought up within Nextcloud at https://github.com/nextcloud/server/pull/15124#pullrequestreview-227243101

**Comment by skjnldsv** [comment]
Fix in https://github.com/apvarun/toastify-js/pull/22
