### ISSUE TITLE
Do i need additional css for backgroundColor to work

### ISSUE THREAD

**Issue by drnkwati** [apvarun/toastify-js#3]
Hi
I copied your example from docs but it doesn't work. Do I need additional CSS for it to work?

Toastify({
    text: "This is a toast",
    duration: 3000,
    destination: 'https://github.com/apvarun/toastify-js',
    newWindow: true,
    close: true,
    gravity: "top", // `top` or `bottom`
    positionLeft: true, // `true` or `false`
    backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)"
}).showToast();

thanks

**Comment by apvarun** [comment]
Hey @drnkwati ,

In order for the library to work, you need to add both toastify.css and toastify.js to your HTML document.

And also your HTML body needs to contain some data as the toast messages are mounted on to the body.

Checkout the attachment here.
[test.zip](https://github.com/apvarun/toastify-js/files/1590256/test.zip)

**Comment by apvarun** [comment]
The latest release adds support for modules which can be used along side existing bundler like webpack.

You can install it from NPM using the command
`
npm install toastify-js
`
