### ISSUE TITLE
Callback or promise on click toast

### ISSUE THREAD

**Issue by mort3za** [apvarun/toastify-js#30]
How can I run a function on click toast?

**Comment by apvarun** [comment]
Thanks for the feature request and PR. It's merged. Will be included in the next release

**Comment by catdad** [comment]
Any update on when the next release will be? It has been 3 months since this was merged, I was hoping to use this functionality.

**Comment by apvarun** [comment]
@catdad : This feature should be available for you to use in v1.6.2
