### ISSUE TITLE
Rails 6 error: Uncaught Root element is not defined

### ISSUE THREAD

**Issue by truongnmt** [apvarun/toastify-js#32]
I'm using Rails 6. Adding `toastify-js` into Webpack, I got this error:

```
Uncaught Root element is not defined
```
Error seem from this line:
https://github.com/apvarun/toastify-js/blob/master/src/toastify.js#L202

**Comment by apvarun** [comment]
Can you reproduce the issue in a repo or online IDE and share here?

**Comment by truongnmt** [comment]
Oh I solved it. It's not an issue from Toastify or Webpack.
Thansk! 😄 

FYI: https://stackoverflow.com/questions/57025027/rail-6-webpack-import-js-third-party-library-uncaught-referenceerror-x-is-not-d
