### ISSUE TITLE
stopOnFocus only applies if close is true

### ISSUE THREAD

**Issue by haydster7** [apvarun/toastify-js#33]
The clearing and adding back of timeout is included inside `if(this.options.close === true)` meaning when this.options.close is unset or false, then stopOnFocus (and the default of stopOnFocus being true) will have no effect

**Comment by apvarun** [comment]
Good catch! Feel free to create a PR?

**Comment by haydster7** [comment]
> Good catch! Feel free to create a PR?

Apologies for the delay, PR submitted

**Comment by apvarun** [comment]
Closing this as the PR is merged and included in version 1.7.0
