### ISSUE TITLE
About ClassName

### ISSUE THREAD

**Issue by LimeZky** [apvarun/toastify-js#34]
When I set classname:error,it didn't have any diffent.

**Comment by apvarun** [comment]
Can you create a minimal reproduction? From what I can see, the class name is being appended to the created Toast. 
_**Reference:** https://codesandbox.io/s/toastify-classname-option-ucfrn_

**Comment by LimeZky** [comment]
Toastify({
  text: "This is a toast",
  className: "error"
}).showToast();
This code is not any different from default.

**Comment by apvarun** [comment]
> _**Reference:** https://codesandbox.io/s/toastify-classname-option-ucfrn_
@LimeZky 
I've updated this Sandbox demo to show a visual difference. I think this would make things clear for you.

**Comment by joaquinwojcik** [comment]
I think this issue has been solved at some point, cause I've seen that demo and it's working well.

![image](https://user-images.githubusercontent.com/3205737/74681476-42790280-51a2-11ea-9ffb-ab2d1e737043.png)

Should we close this?

**Comment by apvarun** [comment]
Closing this as it's fixed now.
