### ISSUE TITLE
Latest Release 1.6.1 is not include commit with onClick callback

### ISSUE THREAD

**Issue by tizis** [apvarun/toastify-js#41]

**Comment by seeyouethan** [comment]
don't use toastify.min.js, it doesn't work ,
try to use https://apvarun.github.io/toastify-js/src/toastify.js  as a local static file.

**Comment by apvarun** [comment]
I believe this is happening since there is no pre-publish build scripts on manual publishing

**Comment by apvarun** [comment]
Closing this. @tizis Please reopen if the issue still persists
