### ISSUE TITLE
Persistent issue

### ISSUE THREAD

**Issue by Icaras12x** [apvarun/toastify-js#42]
I saw the commits included a "persistent" option so I tried duration: 0 or not including duration but the toast will still fade out. Please include the option in the docs or fix it, thanks.

**Comment by apvarun** [comment]
Ah! Thanks for pointing it out. 
For persistent toasts, duration needs to be set as -1.
And for the documentation part, feel free to raise a PR 🙂

**Comment by chasedeanda** [comment]
Here's your PR: https://github.com/apvarun/toastify-js/pull/56.

I wasted too much time debugging this, others shouldn't have to.

**Comment by apvarun** [comment]
Thanks for the PR @chasedeanda
