### ISSUE TITLE
Close / dismiss on click?

### ISSUE THREAD

**Issue by dessalines** [apvarun/toastify-js#53]
Is there any way to close / dismiss on click?

**Comment by apvarun** [comment]
Yes, you can dismiss a toast on click using the onClick parameter.
**Example:** https://codesandbox.io/s/toastify-js-issues-53-2gi84

@dessalines Does this solve your use case?

**Comment by dessalines** [comment]
That did it, thanks!

It might be good to document the methods somewhere, I couldn't find hideToast() anywhere in the docs / README.

Putting the solution here:

```
const dismissableToast = Toastify({
  text: "Dismiss on Click",
  duration: 5000,
  stopOnFocus: true,
  onClick: function() {
    if (dismissableToast) {
      dismissableToast.hideToast();
    }
  }
}).showToast();
```
