### ISSUE TITLE
Any plans to support arbitrary HTML content? 

### ISSUE THREAD

**Issue by hipitihop** [apvarun/toastify-js#55]
For ultimate control and styling, I would like to optionally pass HTML div with arbitrary content as arg. In my case I'd like to include small chart or buttons, small table etc. Any plans for such a feature?

**Comment by apvarun** [comment]
@hipitihop Can you check whether this solves your usecase?
https://github.com/apvarun/toastify-js/pull/54

**Comment by Drumstix42** [comment]
Will #54 be released via the releases page as well? https://github.com/apvarun/toastify-js/releases @apvarun ?

Looking forward to it being available there, as I cannot install via NPM vie current project.

**Comment by apvarun** [comment]
@Drumstix42 I've drafted a new release for 1.8.0

Please find it here
https://github.com/apvarun/toastify-js/releases/tag/1.8.0

**Comment by Drumstix42** [comment]
> 
> 
> @Drumstix42 I've drafted a new release for 1.8.0
> 
> Please find it here
> https://github.com/apvarun/toastify-js/releases/tag/1.8.0

Thank you! I appreciate it.

**Comment by hipitihop** [comment]
@apvarun apologies for my tardy response. Yes #54 should solve my requirements and I appreciate this is now done in 1.8.0, many thanks.
