### ISSUE TITLE
Uncaught Root element is not defined

### ISSUE THREAD

**Issue by afshinhaghighat** [apvarun/toastify-js#57]
adding `selector` as a css ID defined for a DOM element, throws error.

```
Toastify({
    text: message,
    duration: 5000,
    position: "center",
    selector: "main",
    className: `alert alert-info`,
  }).showToast();
```
And the HTML element it is supposed to be added to:

`<main id="main"></main>`

The error being thrown is:

`Uncaught Root element is not defined`

**Comment by RDjarbeng** [comment]
What was the solution for this error? I  am currently facing the same issue. Even when I add 

`selector: '#main'` as the id
