### ISSUE TITLE
Max width problem for firefox browser

### ISSUE THREAD

**Issue by Sandip124** [apvarun/toastify-js#61]
![image](https://user-images.githubusercontent.com/37034590/90672976-b6da4e80-e276-11ea-9128-6ce929028335.png)

In firefox browser, the  toastr is showing more extra space than its content

**Comment by Sandip124** [comment]
the issue is fix in the pull request #62

**Comment by apvarun** [comment]
Released as part of toastify-js@1.9.2
Thanks @Sandip124

**Comment by Sandip124** [comment]
@apvarun  it's my pleasure. actually this is my first open source contribution as i remembered. and i am happy to hear  thanks from you sir.
