### ISSUE TITLE
doesen't work with electron

### ISSUE THREAD

**Issue by KraXen72** [apvarun/toastify-js#74]
sais Toastify is not a function

**Comment by AStoker** [comment]
Could you provide some more details? What does your setup look like and how are you using it?

**Comment by KraXen72** [comment]
i imported the node module in an electron enviroment, and when trying one of the examples it said toastify is not a function

**Comment by AStoker** [comment]
Could you provide a code example of your project? It would help in reproducing the issue and resolving it

**Comment by KraXen72** [comment]
idk man i gave up after i tried to use it for half and hour and just implemented custom toasts. basically i called them in preload, after dom has loaded, everything esle worked, every other library etc. i installed the node module, imported it throught require like you do in electron, and when i tried to use an example from the toastify documentation, it just said Toastify is not a function for whatever reason
