### ISSUE TITLE
NPM package is outdated

### ISSUE THREAD

**Issue by cruzlutor** [apvarun/toastify-js#8]
Hello, nice library.

I have problems to implement `classes` option, I noticed that npm code is outdated.
Could you please update npm package?
thanks

edited: here is a preview https://unpkg.com/toastify-js@1.2.0/src/toastify.js
`classes` option code is missing

**Comment by apvarun** [comment]
The package has been updated in NPM. I will set up a CI for the same for future updates.

**Comment by apvarun** [comment]
Automatic deployment to NPM is now live. No more inconsistency between package versions.
