### ISSUE TITLE
Style Options: "backgroundColor" not working!

### ISSUE THREAD

**Issue by ghost** [apvarun/toastify-js#81]
Toastify({ style: { backgroundColor: '#dc3545' } }).showToast(); **Not Working...**

**default:**
  background: -webkit-linear-gradient(315deg, #73a5ff, #5477f5);
  background: linear-gradient(135deg, #73a5ff, #5477f5);

**Comment by Tigerman55** [comment]
I am just using css to style the background color for now. You can apply `background: inherit;` to the`.toastify` selector, then whatever bg you want to the class you specify in the js.

**Comment by ehudthelefthand** [comment]
I got a similar problem.
Here is mine.
```
Toastify({
                    text: 'Your request was error. Please try again.',
                    duration: 3000,
                    position: 'center',
                    style: {
                        background: '#CC0000'
                    }
                }).showToast()
```
It doesn't work either.

**Comment by ashkan-ahmadi** [comment]
Same. I get the warning: `DEPRECATION NOTICE: "backgroundColor" is being deprecated. Please use the "style.background" property.` but when I use `style: {background: '#000000'}`, it doesn't work.

**Comment by JanSchuerlein** [comment]
Can confirm, the style: {background: ''} parameter isn't working.

**Comment by SergioLaRosa** [comment]
Can confirm too, `style: {background: ''}` doesn't work at all.
